//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.296
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteClioService.ClioWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ClioWebService/", ConfigurationName="ClioWebService.ClioWebService")]
    public interface ClioWebService {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento username del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://ClioWebService/ClioWebService/logoutRequest", ReplyAction="http://ClioWebService/ClioWebService/logoutResponse")]
        ClienteClioService.ClioWebService.logoutResponse logout(ClienteClioService.ClioWebService.logoutRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://ClioWebService/).
        [System.ServiceModel.OperationContractAttribute(Action="http://ClioWebService/ClioWebService/helloRequest", ReplyAction="http://ClioWebService/ClioWebService/helloResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteClioService.ClioWebService.helloResponse hello(ClienteClioService.ClioWebService.helloRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento username del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://ClioWebService/ClioWebService/registrarClienteClioRequest", ReplyAction="http://ClioWebService/ClioWebService/registrarClienteClioResponse")]
        ClienteClioService.ClioWebService.registrarClienteClioResponse registrarClienteClio(ClienteClioService.ClioWebService.registrarClienteClioRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento return del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://ClioWebService/ClioWebService/laboratoriosDisponiblesRequest", ReplyAction="http://ClioWebService/ClioWebService/laboratoriosDisponiblesResponse")]
        ClienteClioService.ClioWebService.laboratoriosDisponiblesResponse laboratoriosDisponibles(ClienteClioService.ClioWebService.laboratoriosDisponiblesRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento username del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://ClioWebService/ClioWebService/loginRequest", ReplyAction="http://ClioWebService/ClioWebService/loginResponse")]
        ClienteClioService.ClioWebService.loginResponse login(ClienteClioService.ClioWebService.loginRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombrePC del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://ClioWebService/ClioWebService/registrarPCRequest", ReplyAction="http://ClioWebService/ClioWebService/registrarPCResponse")]
        ClienteClioService.ClioWebService.registrarPCResponse registrarPC(ClienteClioService.ClioWebService.registrarPCRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class logoutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="logout", Namespace="http://ClioWebService/", Order=0)]
        public ClienteClioService.ClioWebService.logoutRequestBody Body;
        
        public logoutRequest() {
        }
        
        public logoutRequest(ClienteClioService.ClioWebService.logoutRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class logoutRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        public logoutRequestBody() {
        }
        
        public logoutRequestBody(string username) {
            this.username = username;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class logoutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="logoutResponse", Namespace="http://ClioWebService/", Order=0)]
        public ClienteClioService.ClioWebService.logoutResponseBody Body;
        
        public logoutResponse() {
        }
        
        public logoutResponse(ClienteClioService.ClioWebService.logoutResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class logoutResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool @return;
        
        public logoutResponseBody() {
        }
        
        public logoutResponseBody(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="hello", WrapperNamespace="http://ClioWebService/", IsWrapped=true)]
    public partial class helloRequest {
        
        public helloRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="helloResponse", WrapperNamespace="http://ClioWebService/", IsWrapped=true)]
    public partial class helloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public bool @return;
        
        public helloResponse() {
        }
        
        public helloResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registrarClienteClioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="registrarClienteClio", Namespace="http://ClioWebService/", Order=0)]
        public ClienteClioService.ClioWebService.registrarClienteClioRequestBody Body;
        
        public registrarClienteClioRequest() {
        }
        
        public registrarClienteClioRequest(ClienteClioService.ClioWebService.registrarClienteClioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class registrarClienteClioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string nombres;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string apellidos;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string matricula;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string cedula;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string facultad;
        
        public registrarClienteClioRequestBody() {
        }
        
        public registrarClienteClioRequestBody(string username, string password, string nombres, string apellidos, string matricula, string cedula, string email, string facultad) {
            this.username = username;
            this.password = password;
            this.nombres = nombres;
            this.apellidos = apellidos;
            this.matricula = matricula;
            this.cedula = cedula;
            this.email = email;
            this.facultad = facultad;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registrarClienteClioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="registrarClienteClioResponse", Namespace="http://ClioWebService/", Order=0)]
        public ClienteClioService.ClioWebService.registrarClienteClioResponseBody Body;
        
        public registrarClienteClioResponse() {
        }
        
        public registrarClienteClioResponse(ClienteClioService.ClioWebService.registrarClienteClioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class registrarClienteClioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool @return;
        
        public registrarClienteClioResponseBody() {
        }
        
        public registrarClienteClioResponseBody(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class laboratoriosDisponiblesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="laboratoriosDisponibles", Namespace="http://ClioWebService/", Order=0)]
        public ClienteClioService.ClioWebService.laboratoriosDisponiblesRequestBody Body;
        
        public laboratoriosDisponiblesRequest() {
        }
        
        public laboratoriosDisponiblesRequest(ClienteClioService.ClioWebService.laboratoriosDisponiblesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class laboratoriosDisponiblesRequestBody {
        
        public laboratoriosDisponiblesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class laboratoriosDisponiblesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="laboratoriosDisponiblesResponse", Namespace="http://ClioWebService/", Order=0)]
        public ClienteClioService.ClioWebService.laboratoriosDisponiblesResponseBody Body;
        
        public laboratoriosDisponiblesResponse() {
        }
        
        public laboratoriosDisponiblesResponse(ClienteClioService.ClioWebService.laboratoriosDisponiblesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class laboratoriosDisponiblesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public laboratoriosDisponiblesResponseBody() {
        }
        
        public laboratoriosDisponiblesResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="login", Namespace="http://ClioWebService/", Order=0)]
        public ClienteClioService.ClioWebService.loginRequestBody Body;
        
        public loginRequest() {
        }
        
        public loginRequest(ClienteClioService.ClioWebService.loginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class loginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public loginRequestBody() {
        }
        
        public loginRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="loginResponse", Namespace="http://ClioWebService/", Order=0)]
        public ClienteClioService.ClioWebService.loginResponseBody Body;
        
        public loginResponse() {
        }
        
        public loginResponse(ClienteClioService.ClioWebService.loginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class loginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool @return;
        
        public loginResponseBody() {
        }
        
        public loginResponseBody(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registrarPCRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="registrarPC", Namespace="http://ClioWebService/", Order=0)]
        public ClienteClioService.ClioWebService.registrarPCRequestBody Body;
        
        public registrarPCRequest() {
        }
        
        public registrarPCRequest(ClienteClioService.ClioWebService.registrarPCRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class registrarPCRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombrePC;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string idLab;
        
        public registrarPCRequestBody() {
        }
        
        public registrarPCRequestBody(string nombrePC, string idLab) {
            this.nombrePC = nombrePC;
            this.idLab = idLab;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registrarPCResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="registrarPCResponse", Namespace="http://ClioWebService/", Order=0)]
        public ClienteClioService.ClioWebService.registrarPCResponseBody Body;
        
        public registrarPCResponse() {
        }
        
        public registrarPCResponse(ClienteClioService.ClioWebService.registrarPCResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class registrarPCResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool @return;
        
        public registrarPCResponseBody() {
        }
        
        public registrarPCResponseBody(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ClioWebServiceChannel : ClienteClioService.ClioWebService.ClioWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClioWebServiceClient : System.ServiceModel.ClientBase<ClienteClioService.ClioWebService.ClioWebService>, ClienteClioService.ClioWebService.ClioWebService {
        
        public ClioWebServiceClient() {
        }
        
        public ClioWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClioWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClioWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClioWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteClioService.ClioWebService.logoutResponse ClienteClioService.ClioWebService.ClioWebService.logout(ClienteClioService.ClioWebService.logoutRequest request) {
            return base.Channel.logout(request);
        }
        
        public bool logout(string username) {
            ClienteClioService.ClioWebService.logoutRequest inValue = new ClienteClioService.ClioWebService.logoutRequest();
            inValue.Body = new ClienteClioService.ClioWebService.logoutRequestBody();
            inValue.Body.username = username;
            ClienteClioService.ClioWebService.logoutResponse retVal = ((ClienteClioService.ClioWebService.ClioWebService)(this)).logout(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteClioService.ClioWebService.helloResponse ClienteClioService.ClioWebService.ClioWebService.hello(ClienteClioService.ClioWebService.helloRequest request) {
            return base.Channel.hello(request);
        }
        
        public bool hello() {
            ClienteClioService.ClioWebService.helloRequest inValue = new ClienteClioService.ClioWebService.helloRequest();
            ClienteClioService.ClioWebService.helloResponse retVal = ((ClienteClioService.ClioWebService.ClioWebService)(this)).hello(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteClioService.ClioWebService.registrarClienteClioResponse ClienteClioService.ClioWebService.ClioWebService.registrarClienteClio(ClienteClioService.ClioWebService.registrarClienteClioRequest request) {
            return base.Channel.registrarClienteClio(request);
        }
        
        public bool registrarClienteClio(string username, string password, string nombres, string apellidos, string matricula, string cedula, string email, string facultad) {
            ClienteClioService.ClioWebService.registrarClienteClioRequest inValue = new ClienteClioService.ClioWebService.registrarClienteClioRequest();
            inValue.Body = new ClienteClioService.ClioWebService.registrarClienteClioRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.nombres = nombres;
            inValue.Body.apellidos = apellidos;
            inValue.Body.matricula = matricula;
            inValue.Body.cedula = cedula;
            inValue.Body.email = email;
            inValue.Body.facultad = facultad;
            ClienteClioService.ClioWebService.registrarClienteClioResponse retVal = ((ClienteClioService.ClioWebService.ClioWebService)(this)).registrarClienteClio(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteClioService.ClioWebService.laboratoriosDisponiblesResponse ClienteClioService.ClioWebService.ClioWebService.laboratoriosDisponibles(ClienteClioService.ClioWebService.laboratoriosDisponiblesRequest request) {
            return base.Channel.laboratoriosDisponibles(request);
        }
        
        public string laboratoriosDisponibles() {
            ClienteClioService.ClioWebService.laboratoriosDisponiblesRequest inValue = new ClienteClioService.ClioWebService.laboratoriosDisponiblesRequest();
            inValue.Body = new ClienteClioService.ClioWebService.laboratoriosDisponiblesRequestBody();
            ClienteClioService.ClioWebService.laboratoriosDisponiblesResponse retVal = ((ClienteClioService.ClioWebService.ClioWebService)(this)).laboratoriosDisponibles(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteClioService.ClioWebService.loginResponse ClienteClioService.ClioWebService.ClioWebService.login(ClienteClioService.ClioWebService.loginRequest request) {
            return base.Channel.login(request);
        }
        
        public bool login(string username, string password) {
            ClienteClioService.ClioWebService.loginRequest inValue = new ClienteClioService.ClioWebService.loginRequest();
            inValue.Body = new ClienteClioService.ClioWebService.loginRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            ClienteClioService.ClioWebService.loginResponse retVal = ((ClienteClioService.ClioWebService.ClioWebService)(this)).login(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteClioService.ClioWebService.registrarPCResponse ClienteClioService.ClioWebService.ClioWebService.registrarPC(ClienteClioService.ClioWebService.registrarPCRequest request) {
            return base.Channel.registrarPC(request);
        }
        
        public bool registrarPC(string nombrePC, string idLab) {
            ClienteClioService.ClioWebService.registrarPCRequest inValue = new ClienteClioService.ClioWebService.registrarPCRequest();
            inValue.Body = new ClienteClioService.ClioWebService.registrarPCRequestBody();
            inValue.Body.nombrePC = nombrePC;
            inValue.Body.idLab = idLab;
            ClienteClioService.ClioWebService.registrarPCResponse retVal = ((ClienteClioService.ClioWebService.ClioWebService)(this)).registrarPC(inValue);
            return retVal.Body.@return;
        }
    }
}
